### ISSUE TITLE
MD5 and SHA256 + hexbytes doesn't match command-line md5 tool for large files

### ISSUE THREAD

**Issue by sethladd** [dart-lang/crypto#14]
This is probably user error, but for tracking:

```
~/Code/crypto[example*] $ dart example/md5.dart large.txt 
398b8e562429a971168e91ecf7117144
~/Code/crypto[example*] $ md5 large.txt 
MD5 (large.txt) = b5c667a723a10a3485a33263c4c2b978
```

Example code:

```
// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io' show exit, File;
import 'package:crypto/crypto.dart' show MD5, CryptoUtils;

main(List<String> args) async {
  if (args == null || args.length != 1) {
    print('Usage: dart md5.dart <input_filename>');
    exit(1);
  }

  var input = new File(args[0]);

  if (!input.existsSync()) {
    print('File "${args[0]}" does not exist.');
    exit(1);
  }

  var md5 = new MD5();

  await for (var bytes in input.openRead()) {
    md5.add(bytes);
  }

  var hex = CryptoUtils.bytesToHex(md5.close());

  print(hex);
}
```

Running with

```
~/Code/crypto[example*] $ dart --version
Dart VM version: 1.13.0-dev.2.0 (Tue Sep  8 05:13:39 2015) on "macos_x64"
```

**Comment by sethladd** [comment]
Testing further, for very small files, we match http://onlinemd5.com/ and the command-line md5.

Looks like we don't match for very large files (900MB)

**Comment by sethladd** [comment]
cc @sgjesse @iposva-google

**Comment by sethladd** [comment]
Also, fwiw, we also don't match on large files + SHA256

```
~/Code/crypto[example*] $ shasum -a 256 large.txt 
c93dda5f38ad123e7244e88eca3a3037d4dddda22574f5b994a7b00b5f37bed0  large.txt
~/Code/crypto[example*] $ dart example/hash.dart sha256 large.txt 
d28e48d2f0a7d7e6595822b1fad5076a7c6b4fbec563bc7aed75aded0f433f32
```

**Comment by sethladd** [comment]
Verified this checked-mode error on a large file:

```
~/Code/crypto[example*] $ dart -checked example/hash.dart sha256 large.txt 
Unhandled exception:
Uncaught Error: 'package:crypto/src/hash_base.dart': Failed assertion: line 128 pos 12: 'lengthInBits < math.pow(2, 32)' is not true.
Stack Trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      HashBase._finalizeData (package:crypto/src/hash_base.dart:128:12)
#2      HashBase.close (package:crypto/src/hash_base.dart:50:5)
#3      main.<main_async_body> (file:///Users/sethladd/Code/crypto/example/hash.dart:45:43)
#4      _RootZone.runUnary (dart:async/zone.dart:1165)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#7      _Future._complete (dart:async/future_impl.dart:366)
#8      _StreamIteratorImpl._onDone (dart:async/stream_impl.dart:1078)
#9      _RootZone.runGuarded (dart:async/zone.dart:1092)
#10     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#11     _RootZone.run (dart:async/zone.dart:1160)
#12     _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:553)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:591)
#14     _Future._completeWithValue (dart:async/future_impl.dart:376)
#15     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#17     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#18     _runPendingImmediateCallback (dart:i
solate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sethladd** [comment]
CL is https://codereview.chromium.org/1349293002/

**Comment by sethladd** [comment]
Thanks @rmacnak-google !
